### PR TITLE
Halved blobling health.

### PR DESCRIPTION
**Pull request by Profakos**
If this doesn't work out too well, the alternative will be increasing their respawn time.

### CODE REVIEW

**Comment by SuperSayu** [comment]
My default reaction would be to decrease health by a little and decrease spawn rate by a little more (percentage wise).  Alternately, decrease the blobling attack and health; that might even be a bit better, I dunno.

A big theme of blobmode is that when you leave thing be they just get worse and worse.  Nerfing blobs means nerfing their ability to overwhelm you, which is usually due to multiple factors.  You can just change one thing at a time, but you run the risk of thinking about the factors in isolation, when they're really all part of the same (metaphorical) equation.

**Comment by Profakos** [comment]
Their attack is miniscule, their sole purpose is to prevent a single person from facing the blob, which they do well.
How about decreasing their health to 30, so it'll take 3 shots to kill them, instead of four?

**Comment by SuperSayu** [comment]
If you're going to lower it to 3 hits, I would make it more like 25 (or somewhere in the 20-range).  That makes it 3 shots unless someone has previously weakened it; effectively the same, but good luck or good teamwork can make easier work of it.

I would probably also lower spawn rate just a bit; as I say, it's good practice to at least look at all of the variables involved and then tweak them together or separately, whichever is appropriate.

**Comment by Profakos** [comment]
That is what I am doing, testing those two out separately. I have said so in the OP that I would alternatively try out changing the respawn time, to see what impact these changes would do seperately, before testing out both of them at the same time.
Isolating parts of the problem before testing out changes to multiple things help finding out which bit has more weight.

**Pull request merged**
