### PR TITLE
Grand Merge Part  5: Remember remember the merge of November [Ready for testing]

### PR DESCRIPTION
**Pull request by Profakos**
Merging the cold of feature freeze

### CODE REVIEW

**Comment by Profakos** [comment]
Contains an important fix for the singulo getting stuck on lattices, making it stuck outside PA range.

**Comment by Profakos** [comment]
I am at the Grand Window Replacement PR. This might... take a while, but I already have half the station done, taking care to check for wire/pipe/blast doors and such. Hopefully it will go well.

**Comment by Profakos** [comment]
Meant to be wall refactor..... ;-; 
Anyways: there was a giant window and firelock replacing PR I had to merge I hope it went ok. Added some grilles and constructions that we were missing surrounding the station (the one near the mining shuttle is especially cool)

**Comment by Profakos** [comment]
Almost done with November. I also saw a recent nice bar redesign that is still unmerged on TG, which puts down a few poker tables on the counter area and gives bartender a safe of MONEY, so the bartender can be a casinotender too. ;-;

**Comment by Profakos** [comment]
I am at "Splits each z-level into a different map file", this is going to be great.

**Comment by Profakos** [comment]
Cleaning up the snowflake check on sayu-chemsprayers, replacing them with an flags = null so they can't be refilled, so they don't outclass the janitor's backpack, and the one that can't be refilled at all should have been using this.

**Comment by Profakos** [comment]
Done with november, I am merging a few important december things, and then it will be ready for tests.

**Comment by Profakos** [comment]
Have to get up to an Ex Act Fix. If this isn't not finished in time, I have to remind everyone to use the solars as the singulo might become stuck outside the PA range, stuck on lattices.

**Comment by Profakos** [comment]
Merge status finished, ready for testing. Got up to critical merges.

**Comment by Profakos** [comment]
Testing revealed a map bug, fixing asap

**Comment by Profakos** [comment]
Done done

**Comment by SuperSayu** [comment]
Brig wire fixes 2: Electric Bug-undo?

**Pull request merged**
