### PR TITLE
Grand Merge Part 1: July [READY]

### PR DESCRIPTION
**Pull request by Profakos**
Properly merges things, using the cherry pick command, instead of copypasting them. There will be less conflicts this way.
Note: due to the horrible way merging conflicts works, some changes will show entire files. If this happens, I will state the actual changes. 
I will be merging things one by one, and will make checks on a case by case basis, based on things I merged manually that updates these files.  The reason on why I have to resort to "git cherry-pick", is because if I use "git merge", it merged commits that has not been merged yet entirely up to the selected time.
I will test everything deeply, to make sure nothing broke. I will get the server up to date in a few weeks, rather then a few months.

Everyone, please monitor this pull and point out merge errors that slip past by me.

### CODE REVIEW

**Comment by Profakos** [comment]
I'll have to go over a bunch of things I already merged, to remove merge conflicts properly.
Do not worry, I will squash the commits. All in all, the proper git way is much, much faster indeed.

**Comment by Profakos** [comment]
The next merge will contain the moving of soap and banana peel defined around, I have to be careful to keep our own edits to those.

**Comment by Profakos** [comment]
Dropper refactor merged. Made sure pepper can still sniff them.

**Comment by Profakos** [comment]
The link to the rules is now opening an actual webpage instead of a built in html file locally. Could you please add the contents of our rules.html to a rules page on the sayusite?

**Comment by Profakos** [comment]
Currently on rolling chair tweaks, and I found out that the reason our people flew out the chair was that the fire extinguisher code used B.Move instead of Step, which did not move the office chair.
Currently trying to fix it, so far I have it so that you only slip out one tile from the chair instead of flying far away :U Hopefully I can fix this issue fully soon, it is probably in chair's move.
E:  At least this solves our issue of becoming forever unbuckleable upon using the extinguisher.

**Comment by Profakos** [comment]
I am concerned about how the vending machine initialize will interact with the botany changes (if I understand it correctly, it spawn some plants), but overall it seems safe.

**Comment by Profakos** [comment]
I am up to July 9, did two weeks of things in 4 days _cries_

**Comment by Profakos** [comment]
Narsie is being moved to her own file, currently merging your changes with TG's changes
E: uncommenting the uneatable check, because singulos and narsie shouldn't eat space turfs and holograms, and Narise is also supposed to space constructs.... Other than this and your tile ranges, there was no difference. Either way, the is_type_in_list check will be removed when I merge the singularity_act()

**Comment by Profakos** [comment]
Note to myself: I couldn't find the cigarette inhands in the merge conflicted lefthand and righthand files. They are supposed to be changed to include animation and sprites for all directions.

**Comment by Profakos** [comment]
Almost finished with July. This will not be ready for this week though.

**Comment by Profakos** [comment]
Earlier parts touched a lot of codes for food machinery, and smartfridges, and the next pull is going to be one that splits and moves files. This is going to be a though one, to keep the related changes for.

**Comment by Profakos** [comment]
Food file restructuring is annoying but I am making progress. Removed the "eggs break when stepped on" since we only added that as a bandaid to solve Infinite Chicken Works, which is already solved elsewhere.
Updated pizza box ordering to its more economical and delicious TG version. Four pizzas!

**Comment by Profakos** [comment]
This was a rather large one.

**Comment by Profakos** [comment]
I actually overestimated the length of july. Finished. Do I need to squash the commit though, I am not sure if I can do that automatically without breaking everything I worked on ;-;

**Comment by Profakos** [comment]
Hold on, one last fix. I saw Collen added a global list containing wormholes, when that list already existed. EDIT: nevermind, I fix that when I optimize artifact code

**Comment by Profakos** [comment]
Ah, since that file did not cause any merge conflicts, I didn't know there were duplicates. I actually anticipated that there would be some, and compiled to see if  I got a duplicate definition warning. 
Will fix it tomorrow, with any other further problems that might arise.
Hopefully we can merge these soon to test the live, and so that I could begin working on merging august.

**Comment by SuperSayu** [comment]
The vending machine initialize just vends things randomly to nearby tables.  The seed initialize may randomly create fruit through the seed harvest proc (this happens after vending machine initialization for vended items).  That doesn't seem to have changed so all of that is probably good.

Don't worry about squashing things unless you want the practice.

**Comment by Profakos** [comment]
Alright. In this case, it is finished.

**Comment by SuperSayu** [comment]
You also included a backup map file (generated by Dream Maker when item paths change and you use the auto fixer thing on the map editor as I recall), please try not to add those in the future.

**Comment by Profakos** [comment]
Sorry, I included because I thought having a backup would be good ;-; I'll leave it out next time. 
Either way, thanks for merging, now I can start working on August :O

**Pull request merged**
