### PR TITLE
Grand Merge Part 2: August [READY]

### PR DESCRIPTION
**Pull request by Profakos**
Merging the contents of august. 
I will be more detailed this time, listing all changes in the commit name and/or commit details.

### CODE REVIEW

**Comment by Profakos** [comment]
Next grandmerge commit has some assembly things that seem to  be edits you made for TG (judged on your comments in the files), but not here yet, or the other way around, so I am a bit confused, and need you to overlook the changes. The files are: assembly.dm, holder.dm, infrared.dm, signaller.dm, voice.dm, glass.dm (why did these have no absolute paths ;--;)
A change tg made is that voice analyzers make sure that they don't have a holder, so you can only record input when it is not in an assembly. Infrared seem to be runtiming when securing, I will try to fix it before committing.
EDIT: the runtime is that the infrared beam can not read the density of the loc

**Comment by Profakos** [comment]
Committing after fixing errors. Summary: all grenades work, however when you open the assembly interface, the igniter sparks (is this intended behaviour? It doesn't even trigger the bomb), voice analyzer has to be filled with a voice sample before it is put into anything (intended behaviour in the code, it checks explicitly checks for this), infrared analyzer, if not inside a holder and is secured, doesn't set the loc properly, and null exception runtimed. Temporary fix: checks if loc is null or not
Changed a few numerical vars that were defined as NULL instead of 0. Everything else was fine.

**Comment by Profakos** [comment]
Next up: trying to wrangle the radio signal PDA alert message to still work after changing to absolute paths

**Comment by Profakos** [comment]
Merging these absolute paths is hell, let us all agree to never ever use relative paths

**Comment by Profakos** [comment]
This was rather arduous, but all is working.

**Comment by Profakos** [comment]
Oh no, the upcoming GUN PR MERGE is full of things that conflicts because I merged the stun overhaul early. I have to be stay strong ;-;

**Comment by Profakos** [comment]
Now merging fingerless gloves. In this commit, tg introduced an OO version of printblocking (no more RNG, it is all or naught, using a flag), so I am removing the clarity var things we had, since it is superflous now.

**Comment by Profakos** [comment]
700 of those 1000 files is AI vox sound edits, amazing

**Comment by Profakos** [comment]
Another batch of absolute pathening. Currently wrestling with our own TK variant.

**Comment by Profakos** [comment]
All the TK works, even splashing people with fuel beakers, and then setting them on fire. Also uses tk_maxrange for the max range. Tested with both mutation and gloves.

**Comment by Profakos** [comment]
Five more absolute path files to merge _cries_

**Comment by Profakos** [comment]
Currently trying to merge Mob Absolutes. I have to make sure creatures inside pipes are safe
E:
Wading through these important files is absolutely nervewrecking

**Comment by Profakos** [comment]
I really hope this files batch was the last in the absolute path-ifying of things

**Comment by Profakos** [comment]
I am so happy about the admin event refactor, now I can fire ANY events, even holiday ones

**Comment by Profakos** [comment]
Next commit fixes TG map. When I am done wit august, before porting september I will make the AI sat in another Pr, finally ;-;

**Comment by Profakos** [comment]
This commit also intended to make the centcomm ferry move by asking an admin via the ferry console. However, it had a different typepath then the old one, so I didn't replace our one (which is intended for sandbox). We might need to merge the two.

**Comment by Profakos** [comment]
Next commit includes a new config option, which is the displayed station name, please set it.

**Comment by Profakos** [comment]
Full august ETA sometimes next week. I'll need help with the assembly problems mentioned above. If I am finished earlier, I might copy over the AIsat too.

**Comment by Profakos** [comment]
Merging a gigantic span classifying thing. The number of /reds and /blues finally decreased.
Also this is becoming a monolith oh no

**Comment by Profakos** [comment]
Note to self: the previous PR managing hairs added sidetail4 without adding a sprite for it. Commenting out that hair style for now.

**Comment by SuperSayu** [comment]
The thing with the igniter sparking is because the assembly_holder attack_self() makes both assemblies activate(), and sparking is what happens when you activate an igniter.

Absolute paths are honestly kind of annoying in some circumstances, mostly just when writing code but also in some cases it makes a file harder to read, in my opinion.  Nevertheless you're probably right and we should just always use them.

> Wading through these important files is absolutely nervewrecking

I know exactly what you mean, and I wrote one half of the code that I'm comparing.

**Comment by Profakos** [comment]
Imho absolute path make finding proc definitions much easier, I got lost in all these indentions all the time.

Also, looks like I might be finished with august in a few minutes after all, except for the SayCode merge, which I will keep for next time, and a thing where only admins can see who is readied, I don't think our players would appreciate that.

**Comment by Profakos** [comment]
Ready to merge post today's games.

**Comment by Profakos** [comment]
Tested atmoses, gases seem to live peacefully, so all is well and ready.

**Comment by Profakos** [comment]
My git ignore snuck in, but actually it only adds the following files to it:
data/appearance_full.ban
data/banlist.bdb
data/job_full.ban
data/job_fullnew.bdb
Which should have been inside it already! ;-;

**Comment by SuperSayu** [comment]
You did include some thumbs.db which is a windows file intended to show a folder full of icons as thumbnails.  We don't want those, but it's not a big deal.

**Comment by Profakos** [comment]
Thank you, I will begin livetesting with the people soon, and then begin on September and Bugs.

**Pull request merged**
