### PR TITLE
Grand Merge Part 6, Decemmerge: baby, it's code outside [READY]

### PR DESCRIPTION
**Pull request by Profakos**
It is time for wintery and xmas items.

### CODE REVIEW

**Comment by Profakos** [comment]
Chemistry reagents were split into multiple files. Are there are sayustation only reagents besides morphine?

**Comment by Profakos** [comment]
Snack machine is not of the refillable type anymore, as its code and usage would have conflicted too much with the new Chef's Compartment code. But now the chef can bring food to every dispensers. Also could sweet talk their way into departments to foodfill their vendors, yum.

**Comment by Profakos** [comment]
Cleaning up the loose var on the hat, as it was only used by hat_fall_prob, which was completely unused. All it did was merge conflicting every time.
If it is put back, it has to be proc on the hat. The proc return 10% chance, or 0% if it has any flags or armor value. The proc is overriden by wizardhats to be always 0%. Or something like this.
Either way, the current loose field is making hat unmaintainable: every conflict adds 10 minutes of conflict searching.

**Comment by Profakos** [comment]
New configuration option: allow ooc emojis. This is important to be on

**Comment by Profakos** [comment]
New config options: allows players to see their admin notes

**Comment by Profakos** [comment]
By popular request, Undead Rising is a Halloween/Badmin Only event

**Comment by Profakos** [comment]
Almost done, I am on December 30. I'll have to go up to January 4 for important fixes, stopping right before Carn's subsystem rewrite, oh boy.

**Comment by Profakos** [comment]
I decided to stop right before the Datum Mutations thing, because that would require way too many things to merge from January. It is ready now for testing and possibly merging.

**Comment by Profakos** [comment]
Might throw in a few extra things, like the new thing where the opacity value of kudzu is set so if you click on a kudzu tile, you'll click on the kudzu anywhere you click. Will replace our locate kudzu loops with it. It is not needed for this merge and testing, so it can wait to be in another PR.

**Comment by SuperSayu** [comment]
I had no idea our hallucination event probability was higher than standard.

I don't really care about reducing the undead rising to event/badmin only, it's not really thematically tied to the station and needs tweaks to not be quite so demanding on the cpu anyway.

I honestly kinda am upset that you dropped the healing radiation and I wish you would reconsider it in the future.  Granted antagonists are people most likely to want people dead, and so they are disproportionately affected, but as an event it can create extremely varied changes to the situation.  In fact, it might make more sense to revive dead people at the same time--that would allow dead antagonists a chance, although given the metagame, it would simply mean more corpses chucked out the station.  (That's really a problem with metagaming and not a problem with the event, though.)

Additionally, the entire category of "advanced radstorms" is interesting and adds depth to the whole "space is hazardous and weird" dynamic of ss13.  Yes, normal radiation makes people sick.  Granted, the gene-modding radstorms are too powerful to be frequent, and you can only drop them so low.  But there has to be SOMETHING that can just roll over the station in a wave and change things up.  If it could turn random items into artifacts or make a whole bunch of floor plating pop off, that would be cool too.  Adding viruses makes no medical sense but would be mechanically okay, if they were non-threatening diseases (coughing, etc).  Any other temporary or semi-permenant effects would honestly be pretty cool, even if it was just turning random walls transparent for like a minute.

I'm not going to overrule you but think about it.  Right now you're mostly just merging tgcode and dealing with the codebase as-is, but additions are cool too.

**Comment by Profakos** [comment]
I like advanced radiations, just not the healing one.
I would rather make it remove all disabilities and/or powers of the affected people, as it ties in more with the  theme of radiation affecting your DNA, and removing facial disfigurement if someone had any. This would also effect skeletons too I suppose since they have the disfigured flags, but skeletons growing a face would be funny.

**Comment by Profakos** [comment]
Also normal radstorm already have a chance to give superpowers and disabilities either way. I didn't change our guaranteed only superpower radstorm though.

**Pull request merged**
