### PR TITLE
Grand Merge Part 9: Easter Western [READY]

### PR DESCRIPTION
**Pull request by Profakos**
March end and april included.

New config options:
The following options, when uncommented, will disable wizards from learning certain spells
# NO_SUMMON_GUNS
# NO_SUMMON_MAGIC
# NO_SUMMON_EVENTS

Removes mutant color allowed config option. Mutant colors are now always enabled.

Removed the following:
# CONTINUOUS_ROUND_REV
# CONTINUOUS_ROUND_WIZ
# CONTINUOUS_ROUND_MALF
# CONTINUOUS_ROUND_BLOB

Added the following:
# CONTINUOUS REVOLUTION
# CONTINUOUS GANG

CONTINUOUS WIZARD
CONTINUOUS MALFUNCTION
CONTINUOUS BLOB

MIDROUND_ANTAG WIZARD
MIDROUND_ANTAG MALFUNCTION
MIDROUND_ANTAG BLOB

The first one means if it is not commented out, the round won't end with the antagonist's death. The second one, if it is not commented out, will turn into a new gamemode with the antagonist's death.

Shadowling game mode has a probability config setting

abductor_scaling_coeff was also added.
New tips added to the tip file.

### CODE REVIEW

**Comment by Profakos** [comment]
Surgery artifact changed to giving back missing blood, mending bones, removing embedded items.

**Comment by Profakos** [comment]
Next commit will be tricky as it adds Pet Collars, like the ones we had. The PR is: #8427 
This also repathes pets as simple_animal/pet/restoftheirpath so I have to repath pepper too, properly.
I don't know how to merge this with our collars, as these collars work only on simpleanimals, however, they become visible on their  mob sprites, and also capable of renaming them like ours. Also they are activeley maintened, they received tweaks and fixes later. 
Will pause this merge until this is resolved.

**Comment by SuperSayu** [comment]
The collars there should work to completely replace existing collar code.  The code is badly done anyway; the definition is here: https://github.com/SuperSayu/-tg-station/blob/sayustation/code/WorkInProgress/Sayu/misc.dm#L51
and the attackby code is here: https://github.com/SuperSayu/-tg-station/blob/sayustation/code/modules/mob/living/simple_animal/simple_animal.dm#L365

Looking at their code I don't see anything that is missing that's in my code, except forcing some mobs to keep their existing name, which is a miserable hack anyway.

**Comment by Profakos** [comment]
Alright. It has been done.

**Comment by Profakos** [comment]
Gigantic Life refactor incoming, beware.

**Comment by Profakos** [comment]
Arrived to april 1. Not many left.

**Comment by Profakos** [comment]
Next one would be a really big thing, rework of closet overlays, which will be a bit pain to merge because we have hackable closets and I have to figure out how to make that mergeable with that, gah. If there are no outstanding bugfixes that are absolutely neccessary to merge, I might declare this merge PR finished at this place, but I'll try.

**Comment by Profakos** [comment]
sayuwizard magic  projectiles might act weird because of #8687, and I am not sure how to merge it in them, besides removing the calls for the now nonexistent bumped var

**Comment by Profakos** [comment]
Incoming Object Based Lightning System! Beware!

**Comment by Profakos** [comment]
Generic Action\Action Button System incoming! It works with spells even, and has examples of it with tg spells. There is a proper AddSpell proc too, now.
Mime powers got them too!

**Comment by Profakos** [comment]
Done for now. Time for testing. Also I am up to april 17th.

There will be a few bugs with locker doors, but the fix for them is a bit far.However if neccessary I'll try to get up to it.

**Comment by Profakos** [comment]
Adding a few more things.

**Comment by Profakos** [comment]
No more things will be added.

**Comment by Profakos** [comment]
We tested it for a while last night, didn't see any glaring errors.

**Pull request merged**
