### PR TITLE
Various Ports [READY] 

### PR DESCRIPTION
**Pull request by Profakos**
Currently included features
- autolathe and protolathe bugfixes, protolathe has a x5 and x10 button
- many fixes
- adding myself to admins.txt
- UI button activated implants. I had to fix chem implants, they were broken on TGcode
- Slot machines! Adding them on the map, and a coin mint too.
- RWalls south of singularity, as seen on TG, because meteors hitting the emitters is sad. Also safer to go around the station.
- Mining rebalancing & Medipens
- Fixes wormhole jaunter runtime
- Various cargo things (including this pull https://github.com/tgstation/-tg-station/pull/4855/files  (and without this the syndie bundles might runtime)
- Collapsable Rollerbeds & Beautiful  Crew Computer
- Roundstart and roundend info tweaking
- Ear damage healing chemical
- Retrovirus fix
  All done.
  
  This really has turned into a monolithic behemoth : x

### CODE REVIEW

**Comment by Profakos** [comment]
All done.

**Comment by SuperSayu** [comment]
That trick with initial() in #4855 is absolutely ridiculous.  I at once understand it, and cannot fathom it, all at once.  The syntax and its use is clear, but it breaks my mental model of how variables work.

**Comment by Profakos** [comment]
Probably the magic of script based languages. This is the first time I have met a language that allows you to see the variables of a thing that doesn't exist.

**Comment by Profakos** [comment]
Ah, the documentation says it returns the Compile Time variable value.

**Comment by Profakos** [comment]
Whoops

**Pull request merged**
