### PR TITLE
July 2015, part 2 [READY]

### PR DESCRIPTION
**Pull request by Profakos**
July 2015, part 2

### CODE REVIEW

**Comment by Profakos** [comment]
As the next mergable thing removes the var/ from every argument from procs, for they are unneeded, and it edits every file, it will be in a different PR. Oh dear.

This is finished once i add misc fixes

**Comment by Profakos** [comment]
Ready I guess, there are a few things i would prefer to add, but I don't want to slog through the 800+ changed files from the next merge

**Comment by Profakos** [comment]
Eventually I will do it though, just not right now.
They also changed things like thing(M as mob) to thing(M)

**Comment by Profakos** [comment]
Thanks to the code that logs active turfs, I have found and slain most of the map errors. The rest of them are seem to be caused by vents hooked up to large air canisters, and mining tunnels and secret rooms.

**Comment by Profakos** [comment]
Ready for now, I'll add the many file long param tweaks in the next merge, I decided.

**Comment by Profakos** [comment]
Ah, someone found out why the vents on the AI sat cause active turfs: their temperature is set to a value instead of a default one. I'll fix them too today.

**Comment by Profakos** [comment]
All active turfs removed, added a hammer/gavel to the courtroom, edited escape alone to reflect the changes it received

**Comment by SuperSayu** [comment]
> the next mergable thing removes the var/ from every argument from procs, for they are unneeded, and it edits every file

Whoever merged that shit on tg is stupid as hell.  Yes, it's unnecessary, but it standardizes syntax between function definitions and the other places in code, plus the DM editor (and other code editors) highlights the keyword var which, first, gives visible space in between var names, and second, makes it easier to find where that variable is declared, if it's in the function parameter list.  Removing it across the board means they've made the absolutely godawful choice of making that their coding standard which is only going to be more confusing to new coders.

**Pull request merged**
