### PR TITLE
Tweaks on objectives

### PR DESCRIPTION
**Pull request by Profakos**
*Made reagent objectives Wizard only, as they created weird and awkward
storylines, because nor their absence is noticed, nor does it create
problems when they are found. At least with wizards, it forces them to
spend some time in a location.
*Removed balloon objectives. It was rude, and was already removed.
*Trimmed construction board objectives again, leaving in the AI core
one. Added scientist and roboticist to the banlist, because they have
access to imprinters, and the board requires only glass and sacid.
*Adjusted difficulties to the standards (3: steal something
reproduceable, 5: steal something unique)
*Adds CE magboots to the map

EDIT: 
Fixes non ninjas getting ninja objectives. The Steal datums's Possible Items list were collected from datum/objective_item, thus including specials and stacks.

### CODE REVIEW

**Comment by SuperSayu** [comment]
The magboot fix will already be in the next update, I apologize that it is not in the repo.

The "fix" for non ninjas getting ninja steal objectives is a workaround, not a fix.  If the antagonist filter code worked properly, those objectives would be filtered out for non-ninjas.  Please don't confuse workarounds and fixes, they are vastly different things.

I will not permit the balloon objective to be removed.  It is a challenge objective, like hijacking the shuttle; it is equivalent to traitors "accidentally" getting no telecrystals, just like they "accidentally" don't get codewords.  In most rounds, there will be more than one traitor, in which case they should work hard to find each other.  In the case where they are alone (whether or not they know it), they are forced to use found equipment, which a lot of people already enjoy doing, and there is a lot of it to be found.  Kitchen knives, the hidden butcher knives, clever use of all sorts of profession-related tools, learning to doorhack or apc-hack if they don't know how, whatever.

I have _never_ had a player complain about the balloon hack.  I would be more than happy to respond to adminhelps with suggestions of what they could do with limited access, but I have never had someone ask.  The game is full of extras, and searching for them is rewarding.

I would appreciate more of an argument for removing construction board objectives.  I know that they can be made by R&D, and adding them to the banlist is fine.  However, for people that do not have the time to break into R&D, increase research, etc, they have to break into the secure tech storage, which is possible but not trivial.  If you think that they should be combined into a single random objective like clothing/pda cart/stamps, to cut down on how often they appear, I can work with that.  Alternately, you can be ordered to steal AI and borg upload boards at the same time, which is only a minor addition but is a middle ground.

**Comment by CollenN** [comment]
I don't like the balloon objective, because half of the fun of traitor mode is using your telecrystals to buy items and accomplish your objectives, so randomly having them taken away due to the RNG is not very fun or fair.

**Comment by Jacquerel** [comment]
I made an account to tell you that the balloon objective is bad and I have only not complained about it because I have never received it and wasn't aware that it existed
Why would anyone have even thought that was a good idea in the first place

If you want to challenge yourself to not use any tools you will independently choose to buy a balloon.
"Challenges" arbitrarily forced onto players who have spent all night waiting to get an antagonist role are awful

**Comment by Profakos** [comment]
The ninjas code is not exactly a workaround, for that is how it worked in the original codebase.

I would be okay with the board objectives becoming the same objective the same way clothing steal works, to avoid skewing the balance. 

On top of being rather rude to the players who have been waiting to play with antagonist toys, the balloon objective is also another thing that does not create a good story, for it is also something whose absence is not witnessed, or looked for. The traitor would just spawn it on the shuttle.

E: At least I hope the "Reagents are wizards only" stays in, for they create really boring Traitor rounds.

E2: Also the balloon has been commented out for a few months.

**Comment by SuperSayu** [comment]
Challenges are very rarely "good ideas"; good ideas usually make life easier.   And challenges, since they have a good chance of causing you to fail, can very much be seen as rude or unfun, especially when you are looking forward to them and not looking back on them.  Challenges almost by definition are irritating, debilitating, and caustic.

Succeeding in spite of them is a giant "fuck you" to the assholes who stood in your way.  That's the point.  I don't mind people screaming in frustration, at me in particular, when they get an objective they don't like.  I don't mind being an obstacle that stands in the way of their success.  I challenge them, and you, to be good enough to win in spite of the hardships along the way.  I would personally be displeased to get that objective.  I would keep going anyway.  That's life.

To be clear, the matter is not open for vote.  I am not going to close PRs because of it, but I may revert such changes if they keep appearing in spite of my decision.  If you REALLY want to remove the balloon objective, you are going to have to come up with other challenge objectives or a mechanism to create additional challenges for traitors, because all too often they have it too easy.

**Comment by Jacquerel** [comment]
I think any design that is intended to encourage players to say "fuck you" to the person who implemented it probably just shouldn't have been added.

**Comment by Profakos** [comment]
I do remember now that the balloon objective has been commented out for months, because people have complained about getting it.
A better and neater solution would be making them not spawn with an uplink. That would also prevent them from accidentaly buying something, and also the percentage change would be fixed amount.

**Comment by CollenN** [comment]
I think traitors have it pretty tough anyway already, but in a fair way. Cause, like, they need to steal high-priority items that are often in the rooms of the heads of staff. Preforming a perfect heist is difficult due to fingerprints and clothing fibers - it's rare that a traitor steals something and is never found out. Usually that only happens when someone steals something from a department with nobody in it (and we could put in code preventing that).

Plus, they also sometimes have assassination objectives, which can be very hard if the target has a high rank and is a skilled player. And, again, killing someone leaves a ton of evidence (bloodstains, cries for help, it's even pretty noisy if you use guns or bash someone to death) which often makes it hard to pull off a perfect murder.

A better solution would be commenting out objectives that are too easy (such as booze and reagents) and commenting out traitor items that are too powerful (or increasing the price of such items). Obviously we'd need to vote on which ones to remove. (Parapens would be high up on my 'items to remove' list though)

**Comment by dalmationer** [comment]
This objective basically means that the player is /immediately noticed as a syndicate agent/ unless they hide it, which is risky. I know our server is okay at this and won't immediately lynch someone for having a syndie balloon, but you bet that anyone who has one gets a close eye kept on them. Not to mention that if we have a sec team on it is (theoretically) legitimate grounds for confiscation. As the traitor has no items, it all depends on who is playing what roles. If they're in a head role, or are engineer or some other job with good access, they can theoretically do well, but in almost any other? This is just a huge handicap. Not everyone on here is the same skill level, and it could be immensely difficult for a player who does not have skill at hacking ect.

"Hardcore objectives" like this should either be a /solitary objective/; due to how difficult they are, optional, or just not in the game. Not everyone is good enough to succeed with them, and I suspect it would be easy to feel cheated.
It doesn't feel good to be given a night-impossible objective.

I think it's probably a good idea to either take it out, or make it one that only admins can apply if the antag wants a harder objective. Disapproval for this has been almost unanimous amongst the more outspoken regulars of the server and I agree with them.

Harder/ more interesting objectives would be nice, but truthfully this is just insane.

In the meantime, if anyone does get this objective, adminhelp and I will replace it if I'm online.

**Comment by SuperSayu** [comment]
I just erased an entire mess of independent replies because nobody is going to understand it as a mess of independent replies, but instead as a single argument, which it is not.

I consider it to be an in-character issue, and the following are my criteria as to whether or not to keep the objective:
1) Are the syndicate canonically established as possibly incompetent assholes who are willing to sacrifice agent's lives for no reason? [Y]
2) Can you see the syndicate demand this of an agent--advertising themselves as syndicate while possibly handicapping their ability to function properly?  [Y]

The real question, and the reason why the objective doesn't make sense, is because "The balloon costs all your TC because lol".  I note that nobody has suggested that this should be changed, and I would not expect anyone to suggest that.  Pulling a balloon out of your ass is a personal mark of achievement--it means you are good enough to not need syndicate assistance.  The mere fact that _it may be required_ forces a player to consider what they would do if they could not depend on getting any help.

At this point I am **only** willing to hear arguments against it from people who have, themselves, had the objective, unless those arguments include an alternative way to add more fun or challenge in its place.  Collen's comment is better in this regard, as it is informative and suggests alternatives.  I don't like those alternatives--the easier objectives add variety, and since we have multiple objectives compared to /tg/'s one objective, variety is a good thing--but "shut up and do it" is not a valid argument.

**Comment by SuperSayu** [comment]
Additionally, and I thought I had said this earlier in the thread, I am always willing to change people's objectives, including removing a difficult objective like this.  Dalm, you do not need to consider it going around me, I consider it server policy to do nice things like that for players, and I will gladly do it myself.

**Comment by Jacquerel** [comment]
Why not cut out the middle man and instead let people just buy balloons if they want to make things harder, as they already could (note, this means they now have to do more objectives with no items than they would if they had "buy a balloon" as an objective) rather than force them to ask someone to do it for them

"Buy a balloon" doesn't make sense in-universe as you are bringing the syndicate an item which they sent to you, and does not make sense mechanically because it is forcing a challenge that negates what for most people is a huge draw of playing as a traitor (gadgets!) for a challenge which already exists as optional, which apparently people could just ask you to remove anyway.

But, hey, why not just make the wizard sometimes spawn in the Arrivals Shuttle instead of the WIzard Shuttle? That would certainly be a challenge.

**Comment by SuperSayu** [comment]
It is a fairly basic principle of game design that most people will not voluntarily make their life more difficult, even if they might have more fun as a result.  Most people (myself included) will use most if not all of their telecrystals in each round.

I have the same problem with cheat codes in video games that have them.  If I start cheating when playing a game, I will never stop cheating, because it makes no sense to keep playing the game normally, because "the game" is usually overcoming small, unnecessary difficulties one at a time.  "Skip this challenge" is an incredibly enticing and addictive button, but it can turn a game into... well, something other than a game.  A video of things going as you want them to, with little or no difficulty on your part.

**Comment by Jacquerel** [comment]
Umm... no it isn't?
People can and repeatedly do make things harder for themselves just for the sake of defeating a challenge. Some games reward you for it with achievements for going through without being hit, but even without such things the gaming community is full of people who will make their lives as hard as they possibly can.
Literal thousands of people take part in Pokemon Nuzlocke Challenges purely to make the game more difficult for themselves. I personally know someone who set out to prove that you could win the game with any pokemon by beating Pokemon Gold with only a Sunkern. Nothing in game told them to do that, or popped up with a "good job" when they did so, any more than it would have said "good job" if they used a team composed entirely of the strongest of legendary creatures. If you look on youtube, there are hundreds of people who play Dark Souls with intentionally strange or challenging builds just to prove that they can. People hack mario games specifically to make them harder, to the point of completely bizarre level architecture, because they find the challenge appealing.
The notion that players will always take the path of least resistance is provably and laughably false! 

It takes one click to buy yourself a balloon at the start of the round. Your lack of self control isn't a reason to annoy everyone else with this objective, and I'm not sure why a single line of text makes it that much easier for you.

**Comment by SuperSayu** [comment]
> Literal thousands of people take part in Pokemon Nuzlocke Challenge

http://vgsales.wikia.com/wiki/Pokemon
Sales for mainline pokemon franchises number the tens of millions, per generation.  Let's be generous and suggest 10,000 Nuzlocke challengers worldwide.  That would be an average of about one Nuzlocke challenger per thousand normal challengers, or 0.1%

> hundreds of people who play Dark Souls with intentionally strange or challenging builds

http://www.eurogamer.net/articles/2013-04-12-dark-souls-worldwide-sales-total-2-3-million 
Let's set aside the fact that some of them are doing it for glory, instead of doing it as an average everyday passtime.  Even suggesting that the number of people who play Dark Souls with challenge builds is 20 to 1 what you see on youtube, "hundreds" translates into "a few thousand", which is again, still on the order of one challenger to a thousand regular players.

I said "most people".

**Comment by dalmationer** [comment]
most people don't have the skill to pull it off???????

**Comment by SuperSayu** [comment]
Most people haven't tried

**Comment by dalmationer** [comment]
if you insist we can try it but honestly i get the feeling this is gonna be kinda tedious and hard and awful but whatevs it's your call

**Comment by Jacquerel** [comment]
Numerous people on our server have chosen independently to buy balloons (including me)
I can name at least five, our game average is 12 players and we cap at 20 on the most fantastic of days

That's 25% and probably higher. They just don't do it every round, because why would they?

I know for a fact that people on our server are willing to challenge themselves because I've seen them do it and talk to them on a regular basis. They like to set those challenges THEMSELVES. Forcing something as like having to play with no items on them is not interesting, especially when that option already exists as an option for when they choose to do it themselves.

**Comment by Profakos** [comment]
Closing this. Will remake most of its parts seperately.

**Comment by Profakos** [comment]
How about having 5% of a traitor getting only 2-3 telecrystals instead, with a "We could not supply you with enough crystals" message in their greet text. That way everyone wins: You get the challenge forced on people, and they can at least by a deck of syndiecards.
Current chance is about 4-12%, because of up to three objectives.

**Comment by dalmationer** [comment]
Ok. I don't really like to do this but;
No one i've spoken to except you likes this idea, Sayu.
Remove it, or make it an admin-applied objective for when someone wants hard mode.
to sum it up:
[18:26] <Fuade> That's lame

**Comment by SuperSayu** [comment]
If you want it removed, provide either
1) Sufficient negative feedback from people who have received the objective, or
2) Alternatives

If you cannot provide either then you do not belong as part of the conversation.

**Comment by dalmationer** [comment]
Alternative; "make it an admin-applied objective for when someone wants hard mode."
Feedback; 
[18:26] Fuade No
[18:26] Fuade That's lame

[18:26] Tiktalik i'm with fuade
[18:26] Tiktalik that fucking sucks and is stupid

**Comment by SuperSayu** [comment]
That's not an alternative, it's a middle ground between removing it and keeping it.  I am not asking for a compromise, I am asking for an alternative.

As far as I am aware neither of them has received the objective, and if they did I would be happy to hear about what their rounds were actually like and what effect the objective had on their game.  I am fairly specific in my "I don't want comments from outsiders looking in" rule.  It shouldn't be that hard to grasp why.

**Comment by Profakos** [comment]
Alternative:
Make it a 5% chance that the players telecrystal amount is decreased to 0, or 0-2. This way it is no longer an IC issue of whether the player agrees that the syndicate is incompetent or not. This is functionally identical, yet makes more sense. 
E: It also does not become more common if you have more objectives given, or its chance change based on the number of available objectives.

**Comment by Profakos** [comment]
Reply from Moronis who had that objective last saturday:
"It does seem like a silly objective to have in, as it does limit the antag’s options pretty heavily, especially if they have an assassinate objective or some such. Since traitors only have 10 Telecrystals and the balloon costs all 10, it means the traitors have to be really, really good at doing things without their unique traitor items. I was only able to steal all of the things I stole because I was in supply, for example, meaning I could just buy electric gloves and tools. I was also lucky enough to not have assassination objectives, which would’ve made it way worse to deal with, probably even impossible."

Also I am pretty sure Dalm is relevant, as she has bought the balloon most often of all of us.

**Pull request closed without merging**
