### PR TITLE
August 2015 [Ready]

### PR DESCRIPTION
**Pull request by Profakos**
Adds things for August.

Makes the code compile (caused by #202)

New config options:

```
##Comment this out if you've used the mass conversion sql proc for notes or want to stop converting notes
AUTOCONVERT_NOTES
```

WARNING
Thanks to somem SQL updates, #define USE_BYGEX has to be enabled to run. 
The info about the linux version that is needed for it is available at https://github.com/optimumtact/byond-regex

### CODE REVIEW

**Comment by Profakos** [comment]
Had to mirror the change of singulo pull to singulo decay: it will not unanchor anchored items anymore: it made undeconstructible structures amongst other buggy things.

Reasoning from the mirrored fix: 
singularity_pull() no longer unanchors anchored objects (because it breaks the deconstruction of table/girder/statues/etc, and makes mechs pullable by mobs), but it still pulls them.

**Comment by Profakos** [comment]
I have merged everything from the last two weeks, except for the midround pod launch, I'll test how it works first, if I decide to include it.

**Comment by Profakos** [comment]
unreadies because of important fixes

**Comment by Profakos** [comment]
Important fixes done, but I think I'll wait a bit for more possible fixes before I announce it to be ready.

**Comment by Profakos** [comment]
"If you are going to mirror tg's changes, change decay() to step anchored objects under the given conditions instead of modifying pull()."

Sayu that decay code was originally "If (anchored or die roll successes do this){ unanchor and make it move} else ( call singularity pull)", so on unanchored objects, it always called singularity pull. which makes things step, so this is the case right now. In fact, it was called more often because of the missing check for singularity size! The prob was in the wrong place, should have been around the whole if(anchored)else{}. Also Decay should use the size defines not just the probability magic numbers. : P

I'll see what i can do, but anchored objects will not step, as that makes the bugs the merged fix fixed.

Personally, the singulo ripping up floors and walls into metal sheets and grilles at a chance was more appealing visually.

**Comment by Profakos** [comment]
Few fixes have appeared, got to fix them too.

**Comment by SuperSayu** [comment]
Changing pull()  means that everything in pull range is affected even if it's outside decay range, so do not alter the anchored check.  Because I do not want you to alter the pull() anchored check, you cannot use it to replace decay().  If you need objects to step, put the step code in the function the way it was originally.

> Because of the missing check for singularity size

The decay range changes based on singularity size.

> anchored objects will not step

Clearly they do, because that's how the singulo max-size code works.  I thought the same, but Move() does not actually check for anchored, nor does Enter(), instead all the code that starts an object moving such as the singulo accounts for it.  If the singulo ignores the fact that it's anchored and calls step, it will step.

The reason that I unanchored objects that were pulled by the singularity is so that you can write in effects only when an object first becomes unanchored (machines turning off, etc), and so that those unanchored objects can space drift.  Again, taking that into account, tgcode is buggy as hell, unless they snuck in code to detect and deal with that, which isn't bloody likely.

You can always ask me questions if you don't understand it, but the change you made circumvents the point of the code, and simple before/after tests with two bags of holding would show that they produce different effects.  I get the feeling that you modified it without testing it, which is _kind of_ upsetting?

Honestly if the bug is un-deconstructable structures the proper way to handle it is to have those structures disassemble in decay() since that's essentially the point of the proc in the first place.  I understand that you are only merging tg changes and not really meaning to add features, but that would be the correct solution, and reverting the code is a hack.  Unfortunately, tg doesn't use our singulo code, so we can't count on them to do it for us.

If you can provide me a list of structures and machines made buggy by being unanchored I have no problem fixing them.

**Comment by Profakos** [comment]
"thing will not step" is a stupid thing from me, I misread a thing. They will step if the singulo is big enough, the bug was from unanchoring them, not from moving them, for that I apologize.

I made it edit call pull because after the bit that unanchored things got removed that is all what got left of the proc's content! I think I got confused because the code was 

```
if(anchored && prob(size*10 - dist*5))
    anchored = 0
    step_towards(src,S)
else
    singularity_pull(S, size, dist)
```

what you describe sounds more like 

```
if(!prob(size*10 - dist*5)
    return
if(anchored)
    anchored = 0
    step_towards(src,S)
else
    singularity_pull(S, size, dist)
```

That is why I changed it.

 The things like current_size >= STAGE_FIVE actually decreases lags, because it won't always do the thing. I see if it is combined with the prob(), their forces unite.

**Comment by Profakos** [comment]
Looking at this, because decay range is smaller than the grav_pull range, I have to edit grav_pull values or the eat proc itself instead for this to work nicely. As if the prob() call (which I put back) is not in the pull one, that means the singulo might pull the items that are in decay range, and will ALWAYS pull the things outside of decay range.

```
/obj/singularity/proc/eat()
    set background = BACKGROUND_ENABLED
    for(var/atom/X in orange(grav_pull,src))
        var/dist = get_dist(X, src)
        if(dist <= consume_range)
            consume(X)
        else
            if(dist <= decay_range && !contained)
                X.singularity_decay(src, current_size, dist)
            else
                X.singularity_pull(src,current_size, dist)
    return
```

**Comment by Profakos** [comment]
Testing what happens if I do

```
/obj/singularity_pull(S, current_size, dist)
    if(prob(current_size*10 - dist*5))  
        step_towards(src,S)

/obj/singularity_decay(var/obj/singularity/S, size, dist)
    if(!anchored || size >= STAGE_FIVE)
        singularity_pull(S, size, dist)
```

I still think current_size >= STAGE_FIVE means less things will be moved, but we'll see.

**Comment by Profakos** [comment]
A if(anchored || prob(40) || current_size < STAGE_FOUR) return ..() looks alright to prevent mass throwing though

**Comment by SuperSayu** [comment]
pull() needs the anchored check otherwise it will move anchored objects at any range.  You would quickly discover if you tried this that that is 100% escape rate for the engine.

decay() is only called if the singulo is not contained, therefore only put effects that will free the singulo in decay().

**Comment by Profakos** [comment]
so we end up with 

```
/obj/singularity_pull(S, current_size, dist)
    if((!anchored || current_size >= STAGE_FIVE) && prob(current_size*10 - dist*5)) 
        step_towards(src,S)

/obj/singularity_decay(var/obj/singularity/S, size, dist)
    singularity_pull(S, size, dist)
```

As the checks have to be in pull() as that is always called even when contained, and the target is between grav_pull and decay range, according to the code.

**Comment by Profakos** [comment]
I have setup the singulo with that code, nothing escaped.

**Comment by SuperSayu** [comment]
stop reducing decay() to pull().  decay() exists to do special things to anchored objects when they are close enough.  You cannot put that code in pull(), and there is no reason to try.  Adding a step() in decay does not duplicate code to any real extent, and basically nothing overrides pull () anyway.

**Comment by Profakos** [comment]
Sayu, this is the base code of decay, which did nothing interesting besides calling Pull(). This was what it has always done, except for anchored items which made them step... which is the only thing in Pull()! 

I did not remove any special actions from the base obj/Decay().

**Comment by Profakos** [comment]
I did not touch any other Decay() codes, in other files, they are still doing their special things.

**Comment by Profakos** [comment]
Only the one in item/, but all the change was to put in a missing size check, to reduce the amount of throw_at() calls for items.

**Comment by Profakos** [comment]
The basest version of decay on Atom you made is just a pull() call, sayu
so actually, the /obj/singularity_decay should be removed as it is duplicate, and not needed because the unanchoring should be removed, and without it, it is empty.

**Comment by SuperSayu** [comment]
pull () should never move anchored objects.
decay() handles anchored objects.  

When decay() falls through to pull(), it is either because it's unanchored, and pull() will move it, or it is anchored, and pull() will do nothing.  I could instead have replaced the else clause in decay() with:

else if(!anchored) step_towards (...)

I chose not to because they are exactly the same and using pull () allows me to use a named proc that describes what I'm doing.

Put together a truth table if you don't believe it does anything

**Comment by Profakos** [comment]
Please look at the latest commit, anchored items move now, they just won't become unanchored in the process. I have found out my misunderstanding a few comments above, I apologize again. 

With the removal of the line that removes unanchoring, decay() would become this:
if(anchored and prob stuff)
 make it step
else
call the function whose job is to make it step after checking prob stuff

If you afraid of decay doing the pull things on walls and turfs, this is not a thing, as turfs are not objects, so this does not affect them.

The reasoning again for the removal of unanchoring:
Singularity_pull() no longer unanchors anchored objects (because it breaks the deconstruction of table/girder/statues/etc, and makes mechs pullable by mobs), but it still pulls them. 

Removal of unanchoring happened before, where shuttle hitting things unanchored them.

**Comment by Profakos** [comment]
To clarify, the line currently is: If the thing is not anchored or the singulo is big enough, and the prob() is true, make it step once.

**Comment by Profakos** [comment]
I can really make it do the very same check for anchored items in Decay() and make it step if you really want, it just won't change things functionally.
It still got contained during testing.

**Comment by SuperSayu** [comment]
So first of all for anyone else reading this, the singulo code in question is 90% aesthetic and only comes into play when the singularity is loose on the station, so in terms of how much it matters, it's pretty low.

That said, PL, here is pseudocode:
singularity_pull:
- Move any non-anchored object
- This function should never cause the singularity to escape

singularity_decay:
- anchored objects, with some probability, will move - this does catastrophic things to the map but causes beautiful carnage
- otherwise fall through to singularity_pull(), which moves any non-anchored object

There are additional checks made before decay() is called, for safety.

Whether objects remain anchored or not means nothing to the basic function of decay()

**Comment by Profakos** [comment]
Could you please post the proper code in a code block, or PR it on my github for this PR? It would be faster that way. Sorry. ;-;

**Comment by SuperSayu** [comment]
All you really need to do is remove the un-anchoring code from the existing code:

``` BYOND
/obj/singularity_pull(var/obj/singularity/S, current_size, dist)
    if(!anchored)
        step_towards(src,S)

/obj/singularity_decay(var/obj/singularity/S, size, dist)
    if(anchored && prob(size*10 - dist*5))
        step_towards(src,S)
    else
        singularity_pull(S, size, dist)
```

**Comment by Profakos** [comment]
thank you

**Comment by Profakos** [comment]
Finishing this probably today, the PRs I have to merge look stable. Actual READY state declaration comes tomorrow if nothing bad pops up.

**Comment by Profakos** [comment]
I think it is stable now. Has to be updated post games probably, instead of before them (remember the linux bygex version!)

**Comment by SuperSayu** [comment]
Yeah I am at work sorry

**Comment by Profakos** [comment]
No need to be sorry, I meant that it would be better if it was not merged today, but tomorrow when the games are over.

**Comment by Profakos** [comment]
Have to add a few fixes

**Comment by Profakos** [comment]
Finished

**Comment by Profakos** [comment]
More fixes incoming, mostly because of qdelness

**Comment by Profakos** [comment]
Done once more

**Comment by Profakos** [comment]
eh I'll probably finish up to the recent changelog update, there seem to be a good fix for singulo lag caused by ripping up cables

**Pull request merged**
