### PR TITLE
July start, 2015 [READY]

### LINKED ISSUE #188: Alien color overriding alien hair color
This probably happened while merging newlizards

### LINKED ISSUE #191: Sayurefillable vending machines can not be unscrewdrivered when the panel is open

### PR DESCRIPTION
**Pull request by Profakos**
New config options:

```
## Uncomment to have the game log runtimes to the log folder. (Note: this disables normal output in dd/ds, so it should be left off for testing.
#LOG_RUNTIMES

## Uncomment to give players the choice of joining as a human with mutant bodyparts before they join the game
#JOIN_WITH_MUTANT_HUMANS
```

Gang got set into continous mode by default.

Lets turn on JOIN_WITH_MUTANT_HUMANS it is funny

Could we have Mulligan turned on? It had a chance to fire last night, but it was off, so it didn't happen ;-;

Note: there was a bug about assigning a constant var to something in the grav gen code, it fixed itself when I updated byond.

Tips.txt updated.
Adds lizard_female.txt and lizard_male.txt for randomized lizard names

Fixes #188
Fixes #191

### CODE REVIEW

**Comment by Profakos** [comment]
"Clicks in the darkness" is the title of my new horror movie

**Comment by Profakos** [comment]
by removing mining shuttle console I mean removing its access restrictions, and also a gang fix.

**Comment by Profakos** [comment]
not sure when this is ready, probably when the mutant color selection fix is included

**Comment by Profakos** [comment]
I think I have got to a Good Spot, with the least amount of possible bugs

**Comment by Profakos** [comment]
Merging a few things, mainly harmless features and fixes, they seem safe enough.

**Comment by SuperSayu** [comment]
Mulligan stuff is already turned on as far as I can tell.  I can lower the antag life check  (minimum surviving crew to cause new antagonists) but everything should be set up to allow it.

I am exhausted and will not be doing the code merge tonight, I will see if I can get it done before rounds tomorrow, I am sorry

**Comment by Profakos** [comment]
@ Failed merge: it is ministation, we don't use it. The only way to fix it is to redownload the file, but as we don't use that station, I am not spending time to fix it every time it conflicts. 
@ Mulligan: Last round i checked Check Antagonists, it displayed it off for Traitor. It did pass the time limit I suppose, so it just overwrote the check antags panel's contents, in this case there is no error. Perhaps we have to raise the time limit instead, the number of living people was full station - 1.

**Comment by Profakos** [comment]
Sneaking one last important merge in. And it is okay, no need to apologize ; -;

**Comment by SuperSayu** [comment]
When you are merging the code you have both versions.  The resolve conflict tools for merging will let you keep either copy, or merge them manually.  Assuming tortoisegit, right clicking on a file in the merge conflict list will give you "Resolve with theirs" or something like that so you don't even need to use the diff editor to resolve it.  In the diff editor, you can also just right click and "use this whole file".

It's not an important file but I would prefer not to have junk files in the repo.  Don't worry about it for now.

**Comment by Profakos** [comment]
Station seems to be down, is everything alright with the merge? Might need to turn off away missions because wallsmoothing next to borders has problems, and some of them have walls next to the map border.

**Pull request merged**
