### PR TITLE
Wigs!

### PR DESCRIPTION
**Pull request by CollenN**
This adds wigs to the game, which can be worn in the head slot. You can change the wig style with normal click, and change the wig's color with alt click. These wigs can be found in the ClothesMate, the AutoDrobe, and the MagiVend vending machines.

### CODE REVIEW

**Comment by dalmationer** [comment]
Why are they in the magivender when they don't count as wizard hats, and so can't be used for robeless spells?

**Comment by dalmationer** [comment]
enchant wig

**Comment by CollenN** [comment]
I didn't think that far in advance!!!

**Comment by Profakos** [comment]
Code is alright, no problems.

**Pull request merged**
