### PR TITLE
September2015 [READY]

### PR DESCRIPTION
**Pull request by Profakos**
September 2015, a wip in progress of work.

New configs:

```
##Comment this out to stop admin messages sent anytime an admin disconnects from a round in play, you can edit the messages in admin.dm
ANNOUNCE_ADMIN_LOGOUT

##Uncomment to have an admin message sent anytime an admin connects to a round in play, you can edit the messages in admin.dm
#ANNOUNCE_ADMIN_LOGIN
```

Loading from jobs.txt is finally fixed. I updated it to make our server much more diverse on start, but kept the latejoin amounts.
All the files in config/name were updated.

### CODE REVIEW

**Comment by Profakos** [comment]
CameraBugs were changed to have all their upgrades by default, with no upgrade mechanic, as they were extremely underused. If you have anything against that I won't merge it.

**Comment by Profakos** [comment]
I am skipping the camera bug thing until you reply.

**Comment by Profakos** [comment]
Haha, double airlocks got very borked up with the airlocks being changed to use overlays to conserve space and such.

**Comment by Profakos** [comment]
Loading from jobs.txt is finally going to be fixed. The txt will have to be redone, we have to use the new version as the syntax has been changed. I will put up the version we always wanted to use but couldn't because of bugs in a separate PR.

**Comment by Profakos** [comment]
There seem to be problems with atmos, I'll try to replicate it with the TG map, and if the trouble doesn't persist, rebuild the entire station to the new pipenet.

**Comment by Profakos** [comment]
False alarm! On our map there was a case of stacking pipes leading out of a scrubber, I fixed it. All works now.

**Comment by Profakos** [comment]
This is getting readyish. I think I'll get up to today's cult and outfit datum fixes, and cast Finite Incantatem. However, I'll still need a word about the camerabug change's permit or veto.

Additionaly, I will rebuild the map from the tgmap, if the armoury changes are too hard to port over, because we have an older version of the atmos pipelines/wires/disposals. If I recall, the areas we need to port over if i have to remake it: 1, Vacant office swaps place with garden 2, pepper and the professor 3, artifact labs 4, bomb range maintenance 5, secret lootspawn points 6, hop bedroom 7,  glass floors around the bridge

**Comment by Profakos** [comment]
Phew, there was no need to remake the map, the wires were easy to fix.

**Comment by Profakos** [comment]
Once the camerabug question is answered, this is done.

**Comment by Profakos** [comment]
Oh right have to fix double door sprites too.

**Comment by Profakos** [comment]
And got to wait until a fix for the hats making hair vanish is pulled. 
I  might just replace double doors with two doors again if I can't fix the issue. (they were broken by the airlock update because nobody else besides us was using them)
E: the problem is that the icon state names changed. That should be easier to fix.

**Comment by SuperSayu** [comment]
I'm sorry, I meant to get back to you about camera bugs when you first commented but I got sidetracked and have not been online as much as I want to be.

Making camera bugs full access is not an awful idea, the version I created is underpowered.  If I had a lot of time and people who would playtest it I would try different versions of camera bugs, but just defaulting to full is not awful.

The only thing I would add, if they did not, is either boost to the cost of the thing, or force the interface to only work when held in your hand.  With our low populations, being able to track one person--without using up a hand, essentially undetectably--can mean one hell of a lot.  If you have to take it out of your pocket to get updates on your quarry that's better, although you can still duck into maintenance or even just do it in broad daylight if you don't think anyone is going to look at you.  (Do they have inhands now?  I think they might have added them)

**Comment by Profakos** [comment]
They have inhands yes. It probably only works when taken out, I have to check that ingame. By defaulting to full they mean that the upgrade system is removed completely. Is that still allowed?

Other thing is double doors, it seems easier to replace them with two doors until someone makes the required new sprites for them.
E: I think I'll leave both to a different PR. For now I'll replace the doors with two doors, and ask the chat to help sprite the things.

**Comment by Profakos** [comment]
This is considered done for now, might merge the protolathe somatoray fix if there is still time.

**Comment by Profakos** [comment]
Hum, going to update to the latest changelog merge first.

**Comment by Profakos** [comment]
Unreadies, I think I'll add all of september to this.

**Comment by Profakos** [comment]
I think this does it for September. Camerabug update, double door redux and THE REPIPENING are slated for other PRs.

**Pull request merged**
