### PR TITLE
Stun rework port

### PR DESCRIPTION
**Pull request by Profakos**
Ports the grand stun rework! Everyone is happy ;-;
Rundown: 
- Tasers and ebows are short ranged. There is an ebow rework but that is out of scope of this project
- Disabler beams do high stamina damage, so you need multiple shots on a healthy man to stun, but a single shot would still slowdown. Quarter the energy cost of an electrode/laser and can go through glass doors and windows
- Hybrid taser that can fire disabler beams and taser electrodes, standard equipments
- Eguns shoot disabler beams and lasers
- Borgs have just disablers
- Detective gun's stun is shorter, but does large stamina damage
- Bartender beanbag bullets don't instastun but does HEAVY staminadamage, 80, which is enough to stop people assaulting him

Might test this a bit more but it is basically done.

### CODE REVIEW

**Comment by Profakos** [comment]
Gosh darnit logfiles

**Comment by Profakos** [comment]
Looks like the gravity and singulo logs were already committed to the server one time. Removing them in this pull would clean them up, right ;-; ?

**Comment by SuperSayu** [comment]
I will just remove them from the repo, be careful (you may want to use git ignore, I should have included my .gitignore in the repo)

**Comment by Profakos** [comment]
Yeah, good idea, I will do so. Also this one is almost ready, one last commit needed to make sure the borgs can recharge their disablers.

**Comment by Profakos** [comment]
Finito

**Pull request merged**
