### PR TITLE
Sayustation fixes [ready]

### PR DESCRIPTION
**Pull request by Profakos**
Fixed random chem bottles, they work again without runtiming.

Note, the pills are all random in this bottle, I'll make one that isn't all random too, one day.
Fixed runtime on creating clusterbangs with no payload path
Fixed Tequilla runtime. Caused by its chem ID being tequila and not tequilla now.
These were the important runtime fixes.

### CODE REVIEW

**Comment by Profakos** [comment]
Experimentor bug isolated: it instantiates the items, and the instantiated clusterbuster node tries to instantiate more things. Fixed by making the thing qdel itself if there is no payload defined.

**Comment by Profakos** [comment]
Gosh darnit !payload doesn't return true if the payload is null, hum

**Comment by Profakos** [comment]
Fixing invisible sgt pepper

**Comment by Profakos** [comment]
Missing blurry/druggy/badeye huds investigation report: the human/life() removes them before the screen has time to draw them. Probably related to the MC rewrite? I have to investigate further

**Comment by Profakos** [comment]
MC fix didn't change it, but further tests revealed that this is indeed the issue. Mobtick might be set too high??

**Comment by Profakos** [comment]
Tuns out it was fixed on March 2. Ahum, never mind then. This is ready now.

**Comment by SuperSayu** [comment]
> Gosh darnit !payload doesn't return true if the payload is null, hum

What you are probably looking for is !ispath(payload) or !ispath(payload,/atom).  Any value of payload aside from a typepath will runtime in new().  Non-atom typepaths (why would that ever happen) will not runtime but are invalid for obvious reasons.  You could go further and limit it to movable atoms because why would you spawn turfs or areas, but really the point is, that's the function that does specifically the typechecking you are looking for.

**Comment by Profakos** [comment]
I am already got over that problem sayu, I just didn't put down a return after the qdel call, thinking it would autoreturn. It detected the null.

**Comment by SuperSayu** [comment]
I knew the problem wasn't as quoted, as the !syntax will work on nulls, but
I thought I would mention the type check function anyway, mostly just in
case

**Comment by Profakos** [comment]
Ah, I see, thank you then.

**Pull request merged**
