### PR TITLE
First week of june [READY]

### PR DESCRIPTION
**Pull request by Profakos**
Junery.

Adds the the watchdog and autoupdater from #9411 . They are probably windows only, alas.

### CODE REVIEW

**Comment by SuperSayu** [comment]
Someone noted that the theater backstage is not connected to disposals (elbow instead of T junction).

Also note that I pushed an update with the away mission maps fixed for typepath errors, does not conflict with your pr currently.

**Comment by Profakos** [comment]
Noted, thank you.

**Comment by Profakos** [comment]
Next batch of updates will include the Removal Of Unsimulated Turfs. I am not sure I can merge that without rebuilding the map but I'll try.

**Comment by Profakos** [comment]
unsimulated floors are gone, warning, this might break the map. No update this week is preferable, before throughly checking them

**Comment by Profakos** [comment]
I am away for this weekend, so this won't be completed until I am back. I have to get up to the indestructible turf fixes.

**Comment by Profakos** [comment]
Back to work! soon coming up: turfs store a copy of their base turf for destruction/deconstruction purposes, so you can properly build on asteroids and other such things

**Comment by Profakos** [comment]
I had to remove the fake turf making in explosions because I have no idea how to change the code in gravity decay so that it will play nice with this big backend change. ; -;
Also tested with meteors

**Comment by Profakos** [comment]
Things to certainly finish: recent important Shuttle fix, and the new upgrade update, and fix the changelog, try to fix the ankh as discussed. After that this will be probably ready.

**Comment by Profakos** [comment]
Unless something really important comes along, this is ready. Might add some simple things that are nice to add.

**Comment by Profakos** [comment]
The next commit would be a faster getturf written by the main byond dev, but that is too big and early to include in this PR, it will be left for the next one, so this is completed.

**Comment by Profakos** [comment]
Okay, there is one last thing that I can safely merge, but the getTurf rewrite and anything beyond will be left for next time.

**Pull request merged**
